FROM nginx:alpine

# Remove any existing config files
RUN rm /etc/nginx/conf.d/*

# Copy config files
# *.conf files in "conf.d/" dir get included in main config
COPY ./default.conf /etc/nginx/conf.d/

# copy ssl to /etc/ssl
COPY ./ssl /etc/ssl
# Expose the listening port
EXPOSE 80

# expose 443
EXPOSE 443

# Launch NGINX
CMD [ "nginx", "-g", "daemon off;" ]