FROM nginx:alpine

# Remove any existing config files
RUN rm /etc/nginx/conf.d/*

# Copy config files
# *.conf files in "conf.d/" dir get included in main config
COPY ./default.conf /etc/nginx/conf.d/

# copy ssl to /etc/ssl
COPY /ssl/nginx_bundle_9173987293fc.crt /etc/
#从腾讯云获取到的第二个文件的全路径
COPY /ssl/tgbots.club_key.key /etc/
# Expose the listening port
EXPOSE 80

# expose 443
EXPOSE 443

# Launch NGINX
CMD [ "nginx", "-g", "daemon off;" ]