name: tg_next_web_app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository master branch
      uses:  actions/checkout@v3        

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: './'
        target: /tg_next

    - name: SSH to server and restart application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /tg_next
          # stop container 
          docker-compose down
          # delete tg_next_web_app
          docker rmi -f tg_next_tg_next
          # delete nginx 
          docker rmi -f tg_next_nginx
          docker-compose up -d


